### ISSUE TITLE
Contact Dinna & Michael from Champagne for alle 

### ISSUE THREAD

**Issue by andreasgolles** [prolike/Account-Management#13]
Loyalty program 
Give clients the option to change between credit cards and change other data 

-tlf. 30606155
-kontakt@champagneforalle.dk
contact person: Diana og Michael

**Comment by LouBNielsen** [comment]
Jeg har snakket med Michael (Dinna er konen, og hun har lidt mere styr på hvad de ønsker),
men


De har en wordpress side og der er nu en der er ved at udvikle Reepay bestillingsmodulet selv.

Login er de også ved at få lavet

De er mega pressede - det er jo højsæson. 
Derfor har vi aftalt at vi ringer tilbage til dem i Januar. Der vil de meget gerne høre, om vi kan hjælpe dem med at lave en fordelsklub
